gregberge/svgr

.npmignore, README.md, package.json, src/webpack.js, src/webpack.test.js, webpack.js
You can now use Webpack loader using "svgr/webpack".
=> feat: simplify webpack usage

README.md, src/__snapshots__/index.test.js.snap, src/cli/index.js, src/configToOptions.js, src/index.test.js
=> feat: add option keepUselessDefs

README.md
Fixes #56 
Added
```sh
```
before the example
=> Clarifying cli usage for converting directories

.eslintignore, README.md, src/cli/__snapshots__/index.test.js.snap, src/cli/index.js, src/cli/index.test.js, src/configToOptions.js, src/h2x/removeDimensions.js
I'd like to be able to specify width/height within props, this lets me do that.
@neoziro 
I also took the liberty to sort the config options/defaults/docs. Let me know if you want me to pull that out.
I made them separate commits, so you don't get overloaded with a diff when reviewing.
=> add option to removeDimensions

README.md
Existing documentation implied a string array, whereas the correct usage appears to be:
```js
options: {
icon: true,
replaceAttrValues: [
["#F0F", "currentColor"],
["#FF00FF", "currentColor"],
],
},
```
=> Fix `replaceAttrValues` type in README

README.md
I had some confusion when reading the `removeTitle` option, thought I'd clear things up for anyone else reading it.
=> Make `removeTitle` usage more clear in README

src/configToOptions.js
Minifying the svg ids, basically defeats the purpose of keeping them, and causes various issues.
=> when ids are to be kept, do not minify them

README.md, packages/cli/README.md, packages/cli/package.json, packages/cli/src/dirCommand.js, packages/cli/src/index.js, packages/core/src/config.test.js, packages/rollup/src/index.test.js, yarn.lock
=> feat(cli): support custom filename cases

packages/core/src/plugins/__snapshots__/svgo.test.js.snap, packages/core/src/plugins/mergeConfigs.js, packages/core/src/plugins/mergeConfigs.test.js, packages/core/src/plugins/svgo.js, packages/core/src/plugins/svgo.test.js
Hello! Just got not working plugin when enable `icon` option. 
Problem:
not working config: 
```
{
icon: true,
plugins: [ { removeDesc: false } ]
}
```
working config:
```
{
icon: true,
plugins: [ {}, { removeDesc: false } ]
}
```
Solution: add lodash merge function for concat arrays instead merge them and add test for it.
=> fix(core): not working first plugin when icon option enabled

packages/core/src/__snapshots__/convert.test.js.snap, packages/core/src/convert.test.js, packages/core/src/h2x/__snapshots__/expandProps.test.js.snap, packages/core/src/h2x/expandProps.js, packages/core/src/h2x/expandProps.test.js, packages/core/src/plugins/h2x.js
The use case is flow which warns about inexact spread. My template looks
like this and I need to spread props before any other prop.
```js
const template = (code, options, state) => `
// @flow
// Generated from ${state.filePath}
import * as React from "react";
type Props = {
size?: string | number,
fill?: string
};
const style = {
display: "block",
flex: "0 0 auto",
};
export const ${state.componentName} = ({ size, fill, ...props }: Props) => {
return (
${code}
);
};
`;
```
=> Allow to spread props at the start

__fixtures__/overrides.config.js, packages/cli/src/__snapshots__/index.test.js.snap, packages/cli/src/index.js, packages/cli/src/index.test.js, packages/cli/src/util.js, packages/core/src/config.js
Ref https://github.com/smooth-code/svgr/issues/174
In this diff I fixed loading config from custom path specified in
`--config`.
Current behaviour is loading only `svg.config.js` in directory of
specified in `--config` file. This is not intuitive.
Also fixed the problem of overriding options specified in config by
defaults from cli.
=> Fix config loading

README.md
Original intructions ask you to install svgr and run `svgr` command. This results in an error, `svgr: command not found`. Referencing issue #51, you run `npx svgr`. This results in another error. Key line in logs, `warn deprecated svgr@2.0.0: Please install @svgr/cli, @svgr/core or @svgr/webpack` advices us to then asks us to install `@svgr/cli`. This results in original error again.
I changed Readme to reference this, and following solution, to reduce any confusion going forward and to align with changes made (ie. depreciation to svgr package)
Correct usage requires you to combine the last two recommendations, leading us to `npx @svgr/cli` which works perfectly.
=> Changed svgr references in readme to @svgr/cli

packages/core/src/h2x/__snapshots__/toReactNative.test.js.snap, packages/core/src/h2x/toReactNative.js, packages/core/src/h2x/toReactNative.test.js
New version of react-native-svg support Mask & Image:
https://github.com/react-native-community/react-native-svg/blob/master/index.js
- yarn build
- yarn test --watchAll
=> feat: allow Mask & Image on React Native

packages/webpack/src/index.js
When use `@svgr/webpack` as loader in webpack and has a `babel.config.js` in project at the same time, svgr will read `babel.config.js` which will be merged to it's own config. This may causes some problems. For exmaple when I use [react-hot-loader](https://github.com/gaearon/react-hot-loader) in `babel.config.js`, svgr throw an error
```
TypeError: Property value expected type of string but got null
```
Of course, if I change my own `babel.config.js` to `.babelrc`, then I can solve the problem because of `babelrc: false`
So, like `babelrc: false`, `configFile: false` prevent babel reading `babel.config.js`.
This is my `babel.config.js`
when use `@svgr/webpack` to deal svg here is the output
but after add `configFile: false` the output is success
=> fix: prevent babel reading babel.config.js

packages/plugin-jsx/README.md
The relative URLs contained a `/packages` path segment too much which has been removed to match the parent folder.
=> Fix relative URLs to other SVGR Babel plugins

packages/babel-plugin-transform-svg-component/src/util.js
When enabling the `ref` option the compilation will fail due to a `SyntaxError` on the _unexpected token_ `<`:
```sh
ERROR in ./src/components/molecules/core/ErrorState404/styled/svg/fragments/space.svg
Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
SyntaxError: Unexpected token (2:52)
1 | /* @babel/template */;
> 2 | const ForwardRef = React.forwardRef((props, ref) => <SvgSpace svgRef={ref} {...props} />)
|                                                    ^
3 | 
4 | export default __webpack_public_path__ + "static/space.fea3855e.svg";
5 | export { ForwardRef as ReactComponent }
```
This is caused by the [util function `getExport`][src-util-func] that creates the JSX export statements.
The root cause is that the [Babel's AST template function][babel-doc-template] …
=> [@svgr/babel-plugin-transform-svg-component] Fix parsing error of JSX template export statements

website/src/pages/docs/cli.mdx
Fix documentation leading to issue #261.
As SVGO simplifies colors like `#000000` to `#000`, example was misleading.
=> docs: fix code example for replace-attr-values

packages/babel-plugin-add-jsx-attribute/package.json, packages/babel-plugin-remove-jsx-attribute/package.json, packages/babel-plugin-remove-jsx-empty-expression/package.json, packages/babel-plugin-replace-jsx-attribute-value/package.json, packages/babel-plugin-svg-dynamic-title/package.json, packages/babel-plugin-svg-em-dimensions/package.json, packages/babel-plugin-transform-react-native-svg/package.json, packages/babel-plugin-transform-svg-component/package.json, packages/babel-preset/package.json, packages/cli/package.json, packages/core/package.json, packages/hast-util-to-babel-ast/package.json, packages/parcel-plugin-svgr/package.json, packages/plugin-jsx/package.json, packages/plugin-prettier/package.json, packages/plugin-svgo/package.json, packages/rollup/package.json, packages/webpack/package.json
This PR replaces git+ssh links in repository field with https form for all of the packages. As a consequence, npm will display a link to github on packages sites. See https://github.com/smooth-code/svgr/issues/246 for more details.
The result of a Github badge will be visible in npm pages of the packages.
=> chore(packages): replace repository field with npm-friendly link

packages/babel-plugin-transform-react-native-svg/src/index.js, packages/babel-plugin-transform-react-native-svg/src/index.test.js, packages/babel-plugin-transform-svg-component/src/index.test.js, packages/babel-plugin-transform-svg-component/src/util.js, packages/babel-preset/src/index.js, packages/babel-preset/src/index.test.js, packages/core/src/__snapshots__/convert.test.js.snap, packages/core/src/convert.test.js, website/src/pages/docs/options.mdx
Using an ejected ExpoKit after version 32 prevents `import Svg from
'react-native-svg';` from working, and also prevents the developer from adding
'react-native-svg' as a direct dependency since ExpoKit already provides the
library just behind the ExpoKit svg namespace. See
https://github.com/kristerkari/react-native-svg-transformer/issues/13
This handles that case by allowing a `expo: true` flag to be passed instead of
the `native` option and will create the correct import statement to use Expo's
SVG library as well as prefix all non `<Svg />` components with `Svg.`.
Added an additional test case to show the import statement and the component name prefixing.
=> Add a mode to create react-native svg using expo

website/src/pages/index.mdx
Correct typo in homepage.
`s/Flexbility/Flexibility`
=> docs: typo in homepage

packages/cli/src/__snapshots__/index.test.js.snap, packages/cli/src/dirCommand.js, packages/cli/src/index.test.js
Currently wide output looks bad on half of the screen I use for terminal
```
src/svgs/visibility.svg -> /Users/_________________________________________/src/icons/Visibility.js
```
In this diff I suggest simply cut useless path and get this
```
src/svgs/visibility.svg -> src/icons/Visibility.js
```
=> [cli] output relative destination paths

packages/babel-plugin-svg-dynamic-title/src/index.js, packages/babel-plugin-svg-dynamic-title/src/index.test.js, packages/babel-preset/src/index.test.js, website/src/pages/docs/options.mdx
Fixes #310:  `title` should fallback to SVG's title when titleProps is set to true and no title is provided
I have updated the `@svgr/babel-plugin-svg-dynamic-title` plugin to insert a conditional statement for  rendering title of the SVG. So now, if the `titleProp` is set to true and the SVG has a title element, then the React component will have following conditional statement to render the title
```html
<svg><title>Default Title</title></svg>
```
```diff
<svg>
- {title}
+ {title === undefined ? "Default Title" : title}
</svg>
```
If there is no title in the SVG, then there will be no change in the React component (same is existing).
```html
<svg>
<title>{title}</title>
</svg>
```
I have update the relevant test case and docs for the implemented functionality.
P.S.: This is my first …
=> update(titleProp:true): title should fallback to svg's title

packages/babel-plugin-svg-dynamic-title/src/index.js, packages/babel-plugin-svg-dynamic-title/src/index.test.js, packages/babel-preset/src/index.test.js, website/src/pages/docs/options.mdx
Fixes #314 titleProps=true not working as expected for existing title
We need to handle existing `title` element's children with a different strategy. Instead of looping through children and creating a children, we can instead, use all the children and push them into a title element. And from the conditional statement for fallback title, instead of returning a title children, we return the title.
```diff
- {title === undefined ? "Existing_Children" : title}
+ {title === undefined ? <title>{Existing_Children}</title> : <title>{title}</title>}
``` 
I have updated the test case for the same with different type of existing title elements.
```js
// pass
expect(testPlugin(`<svg><title>Hi</title></svg`)). toMatchInlineSnapshot(
`<svg>{title === undefined ? <title>Hi</title> : …
```
=> Handle the existing title case by using element instead of value (children)

website/src/pages/docs/typescript.mdx
Refactors the example typescript template to match the new import paths of React.
The usage of the generated icons is the same as before. Only the build size should be smaller.
=> docs(typescript): refactor typescript template

packages/core/src/state.js, packages/core/src/state.test.js
fixes #331 - Filenames may contain invalid characters for javascript variable names, so they need to be removed.
Add a few tests to check that the characters are removed.
@neoziro There a few ways to handle this, but I'm not sure which way is preferred.
1. Remove a few known characters that might cause issues (~!@#%&?)
2. Have a whitelist of characters (`a-zA-Z0-9_-`)
With option 1 we may run into more characters later that need to be added. Option 2 might have the issue of a filename with only invalid characters, or characters that are actually valid but are removed anyways (unicode).
=> Fix #331 - Invalid characters in component name

packages/babel-plugin-svg-dynamic-title/src/index.js, packages/babel-plugin-svg-dynamic-title/src/index.test.js, packages/babel-preset/src/index.test.js, packages/cli/src/__snapshots__/index.test.js.snap, packages/core/src/__snapshots__/convert.test.js.snap
- Don't render empty title (fixes #333)
- Preserve existing title attribute if any
Currently when no title is passed and titleProp is set to `true`, we are
rendering an empty title element which is causing some issues. So we
have added a conditional statement for rendering the title element only
if the title props is not falsy. If we have an existing title, that will
rendered by default. Passing the `null` values as the title will cause
also cause the title element for not render even if a default title
exists on the svg.
This PR also add support for preserving title attribute which may be present in the svg file.
```html
<svg><title attr="any">Default title</title></svg>
```
will produce
```jsx
<svg>
{title === undefined
? <title attr="any">Default title</title>
: title
? <title …
```
=> fix(svg-title): dont render empty title

packages/cli/src/__snapshots__/index.test.js.snap, packages/cli/src/dirCommand.js, packages/cli/src/index.js, packages/cli/src/index.test.js, packages/cli/src/util.js
Solves https://github.com/smooth-code/svgr/issues/347
* Do not write to stdout when "silent" option is on
* Update tests
Snapshot test has been added.
=> Add "silent" option to cli

website/src/components/playground/Playground.js
Thanks for the awesome tool. I've been using the playground to convert svg to jsx and I notice that every time I try to copy the jsx code, this dialog appears
Ideally it should be displayed only once. This PR implements that change.
Run the website, go to playground, press cmd/ctrl + c, dialog gets displayed. Subsequent cmd/ctrl + c should not display the dialog anymore.
=> Display CopyFeedback dialog only once

__fixtures__/custom-index-template.js, __fixtures__/custom-index.config.js, packages/cli/src/__snapshots__/index.test.js.snap, packages/cli/src/dirCommand.js, packages/cli/src/index.js, packages/cli/src/index.test.js, website/src/pages/docs/options.mdx
New index.js generator does not cover my cases.
1. need to add `// @flow` on top of the file
2. need to use named export
Both can be easily solved with indexTemplate option.
```
function indexTemplate(files) {
const exportEntries = files.map(file => {
const basename = path.basename(file, path.extname(file))
return `export { ${basename} } from './${basename}'`
})
return '// @flow\n' + exportEntries.join('\n')
}
```
=> Allow to provide custom index.js template

__fixtures__/numeric/2.file.svg, __fixtures__/numeric/file.svg, packages/cli/src/__snapshots__/index.test.js.snap, packages/cli/src/dirCommand.js, packages/cli/src/index.test.js
Ref https://github.com/gregberge/svgr/issues/379
=> Add Svg prefix to index.js exports by default

examples/parcel/package.json, examples/parcel/yarn.lock, packages/parcel-plugin-svgr/package.json, packages/parcel-plugin-svgr/src/asset.js, packages/parcel-plugin-svgr/src/index.test.js, yarn.lock
Fixes #381 
This would probably be a breaking release because it requires users to also replace `parcel-bundler`
=> Replace `parcel-bundler` with `parcel`

CONTRIBUTING.md
It seems Github may have changed its Contributors URL since this was initially set up. The current `href` directs you to `https://github.com/gregberge/svgr/blob/master/graphs/contributors`, which is a broken page. The functioning page is `https://github.com/gregberge/svgr/graphs/contributors`, so I've inlined it in the `href`. 
Functionality on master breaks: https://github.com/gregberge/svgr/blob/master/CONTRIBUTING.md#credits
Functionality on fix branch works: https://github.com/michaeljaltamirano/svgr/blob/docs/update-contributors-link/CONTRIBUTING.md#credits
=> [Docs] Update contributors link in CONTRIBUTING.md

packages/cli/README.md, packages/cli/src/index.js, website/src/pages/docs/cli.mdx, website/src/pages/docs/options.mdx
=> fix(cli): remove confusion between {keep,ignore}-existing

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.js.snap, packages/babel-plugin-transform-svg-component/src/util.js, packages/cli/src/__snapshots__/index.test.js.snap, packages/cli/src/index.test.js
#414 added typescript support (yay!), but there were a couple of incorrect types when the `--typescript` argument was added to the CLI with other args, specifically `--title-prop` & `--ref`. 
For the `--title-prop` arg with `--typescript`, the `title` & `titleId` props added to the `SVGRProps` interface should be `string`, not `String`. The main problem is that the `id` prop in the `<title />` element only takes `string`. But in general `string` should always be used.
For the `--ref` arg with `--typescript` the call to `React.forwardRef` implicitly has a type of `React.Ref<unknown>` but it's being passed to the `svgRef` which has a type of `React.Ref<SVGSVGElement>`.
This PR fixes both of these issues.
I added a new test case for `--typescript --ref --title-prop` in the CLI tests, which …
=> fix(api): Fix typescript types

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.js.snap, packages/babel-plugin-transform-svg-component/src/index.test.js, packages/babel-plugin-transform-svg-component/src/util.js, packages/cli/src/__snapshots__/index.test.js.snap, packages/core/src/__snapshots__/convert.test.js.snap
Already described in: #440 - there is also a demo :D
By wrapping the svg component in a new component at https://github.com/gregberge/svgr/blob/6e7e6b2e73d26d30f64604e0fc627f9ff94079c2/packages/babel-plugin-transform-svg-component/src/util.js#L215 the generic types of React.forwardRef loose the prop types from the svg component. 
This fix directly wraps the component in React.forwardRef without something in between. Not wrapping the component in an empty proxy component also has a slight performance advantage. To accomplish the direct wrap with React.forwardRef I also had to change the order with React.memo: React.forwardRef has to be the first wrapper around the svg component because React.memo itself doesnt forward the ref further - the difference can be seen here: …
=> fix: wrap svg component directly with memo/forwardRef (#440)

README.md
This PR adds a link to the README that points users to the VS-Code extension implementation of SVGR I have worked on. I've gotten some positive feedback on the extension so thought would be good to share a link and make it more easily accessible to devs looking into SVGR and how it can fit into their workflow.
Screenshot from README:
=> Add link to VSCode extension

packages/babel-plugin-transform-react-native-svg/src/index.js
SVGR currently drops `<foreignObject>` tags, even though they're supported by `react-native-svg`.
This PR adds `foreignObject` to the map of recognised tags (`elementToComponent`).
=> Add `ForeignObject` support for react native

packages/cli/package.json, packages/cli/src/dirCommand.js, packages/cli/src/fileCommand.js, packages/cli/src/index.js, packages/cli/src/index.test.js, packages/cli/src/util.js, yarn.lock
Node v10 got fs.promises support with already promisified api. See here https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_promises_api
Also we get helpful mkdir recursive flag which replaces mkdirp and
make-dir packages.
In this diff I replaced util.promisify with fs.promises where possible
and output-file-sync with combination of promisified fs.mkdir and fs.writeFile.
=> Use fs.promises in svgr cli

packages/webpack/README.md
Noticed in the example for handling SVG in CSS that it should be an array with 2 objects.
=> Fix array syntax for SVG in CSS example

packages/cli/src/dirCommand.js, packages/cli/src/util.js, packages/cli/src/util.test.js
The PR is motivated by this issue: [https://github.com/gregberge/svgr/issues/481](https://github.com/gregberge/svgr/issues/481)
The code is quite simple, if the name starts with a number and/or has a hyphen it modifies it, otherwise, it returns the original, I have added the tests and everything seems to work perfectly, I hope it is helpful! 😀
=> Fix: ensure a valid name for exports

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.js.snap, packages/babel-plugin-transform-svg-component/src/index.test.js, packages/babel-plugin-transform-svg-component/src/util.js, packages/core/src/__snapshots__/convert.test.js.snap, yarn.lock
To fix #465 I updated the type annotations for react-native.
I also found to support the eslint rule @typescript-eslint/explicit-function-return-type we would need to add the return type if the typescript flag is present. But I have no idea how to implement that.
I didn't get it with jest. It gave me (w/o changes) so much errors and deprecated snapshots. I lost sight. 
Also I tried to just add to cli/src/index.test.js to 'should support various args', but jest didn't run it.
So I did manual tests:
1.  target functionality
`svgr --native --typescript ../../../__fixtures__/simple/file.svg --silent`
```
import * as React from 'react'
import Svg, { SvgProps, Path } from 'react-native-svg'
function SvgFile(props: SvgProps) {
return (
<Svg width={48} height={1} {...props}>
<Path d="M0 …
```
=> React-Native with TypeScript breaks on typecheck #465

.gitpod.yml, CONTRIBUTING.md, README.md
Hi. 
I work for Gitpod(an online Open Source VS Code like IDE which is free for Open Source) and we're currently on a mission to simplify contributors/maintainers onboarding for cool Open Source projects. 
This Pr adds Gitpod config to the repo to fully automate the dev setup for this project i.e with this config anyone interested in contributing to this project would be able to start a workspace where it will automatically:
- clone the `svgr` repo.
- install all the dependencies in `/` and `/website`.
- run `yarn dev` in `/`.
- run `yarn dev` in `/website` to start the dev server.
This way anyone interested in contributing can start straight away without any friction.
You can give it a try on my fork of the repo via the following link: …
=> make contributions easier via fully automating the dev setup.

website/src/pages/docs/rollup.mdx
When I was loading `@svgr/rollup` in my rollup config, it said that `svgr` is not a function.
When I did the require via the node CLI, i noticed the following
```
Welcome to Node.js v14.15.1.
Type ".help" for more information.
> require("@svgr/rollup")
{ __esModule: true, default: [Function: svgrPlugin] }
> 
```
This PR corrects the documentation for this.
=> docs: require('@svgr/rollup') should be require('@svgr/rollup').default

website/src/pages/docs/options.mdx
SVGR has some internal SVGO config changes that aren't documented which differ from upstream SVGO defaults.
The `dimensions` option was documented in a way that was easy to be confused (previously the `Default` was `false` but was later documented as `true` without updating the description or CLI option), this has been better addressed.
Additionally collapsed some lines that were split to multi-line, and minor grammar fixes or improvements.
---
Resolves: https://github.com/gregberge/svgr/issues/547
Resolves: https://github.com/gregberge/svgr/issues/550
=> docs: Better explain gotchas with the config options

packages/webpack/README.md, website/src/pages/docs/webpack.mdx
After Webpack 5, the `issuer` prop type is no longer supports `{ test: RegExp }` condition. So it's better to keep this repo up to date as well. Since Webpack 4 also supports the example in this PR, I assume it should also cover the Webpack 4 too.
Before:
After:
=> Few adjustments for Webpack 5

packages/hast-util-to-babel-ast/package.json, packages/hast-util-to-babel-ast/src/handlers.js, packages/hast-util-to-babel-ast/src/index.test.js, yarn.lock
This patch fixes the issue reported in #516. The fix targets `@svgr/hast-util-to-babel-ast`. The handler for XML text parsing now creates a string literal which content is entity-decoded via the [`entities`](https://www.npmjs.com/package/entities) package. The reference for XML entities is available here: https://www.w3.org/TR/REC-xml/#sec-internal-ent
To be fully XML compliant, we would also have to substitute external entities, those declared in the body of the document. However this is a substantial endeavor out of scope of this fix.
Two tests have been added in `hast-util-to-babel-ast` test folder. See capture below:
=> Fix XML entities in generated JavaScript

packages/webpack/README.md, packages/webpack/package.json, packages/webpack/src/__snapshots__/index.test.js.snap, packages/webpack/src/index.js, packages/webpack/src/index.test.js, yarn.lock
Should offer support for #354 and #473. I originally tried to use the webpack loader with NextJS and TypeScript. I consistently got a SyntaxError when I had `{typescript: true}` in the options. This PR adds the `@babel/preset-typescript` preset if the typescript option is enabled. It also automatically sets the preset-typescript options to `{ allowNamespaces: true, allExtensions: true, isTSX: true }` which enables processing the `.svg` extension as typescript.
A bug I've noticed that I haven't fixed is if you have a separate config file `.svgrrc.js` the `options` object in the webpack loader will be empty. I'll take a look into that if I have enough time!
The additional changes in other files are due to me running `yarn format` on the repo.
Added an additional test case to the webpack …
=> Added webpack typescript preset configuration

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.js.snap, packages/babel-plugin-transform-svg-component/src/index.test.js, packages/babel-plugin-transform-svg-component/src/util.js, packages/core/src/__snapshots__/config.test.js.snap, packages/core/src/__snapshots__/convert.test.js.snap, packages/core/src/config.js, packages/core/src/convert.test.js, packages/rollup/README.md, packages/webpack/README.md, website/src/pages/docs/rollup.mdx, website/src/pages/docs/webpack.mdx
related: #557, https://github.com/kazijawad/esbuild-plugin-svgr/issues/2
By default, when `@svgr/webpack` is the only loader handling svg files, it will always export the SVG React Component via default export. However, there may be cases where we prefer always exporting it via named export.
In light of this, I'd like to propose adding a ~~`forceNamedExport`~~ `exportType` (https://github.com/gregberge/svgr/pull/584#pullrequestreview-755561936) config option to explicitly export the React Component via named export.
In Webpack config:
```js
{
test: /\.svg$/,
use: [
{
loader: '@svgr/webpack',
options: {
exportType: 'named',
},
},
],
}
```
This will allow us in React side:
```js
import { ReactComponent as Star } from './star.svg'
const App = () => (
<div>
<Star />
</div>
)
```
added test …
=> Add option to explicitly use named export

__fixtures__/simple-existing/index..js, package.json, packages/core/package.json, packages/core/src/index.d.ts, packages/core/src/index.errors.ts, packages/core/src/index.types.ts, yarn.lock
Following https://github.com/gregberge/svgr/issues/513 I added TypeScript declaration file (`index.d.ts`) to `@svgr/core` with @jschaf  https://github.com/gregberge/svgr/issues/513#issuecomment-829717133 modified a little.
This will help for easier auto-completion and for other library authors that use TypeScript and want to pass type-safe params to `@svgr/core`
**NOTICE**: as https://github.com/gregberge/svgr/issues/513#issuecomment-829717133 notes - the types are not 100% compatible but I think for most people it will be good enough (and it can improve it over time).
I use https://github.com/ai/check-dts for checking `.d.ts` files
- `index.types.ts` shows positive tests
- `index.errors.ts` includes improper usage of the library
I added it to the CI too.
=> Add TypeScript declarations to `@svgr/core`

packages/cli/src/util.js, packages/cli/src/util.test.js
This PR fixes the `formatExportName` for single names. For example, for names like `foo` it should export `Foo` name instead `foo` as named export in index.js file. This will fix the named exports in index.js.
**Actual output:**
```js
export { default as foo } from './foo'
export { default as bar } from './bar'
export { default as FooBar } from './foo-bar'
```
**Expected output:**
```js
export { default as Foo } from './foo'
export { default as Bar } from './bar'
export { default as FooBar } from './foo-bar'
```
The PR is motivated by this issue: https://github.com/gregberge/svgr/issues/481
=> Fix formatExportName for single names

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.ts.snap, packages/babel-plugin-transform-svg-component/src/index.test.ts, packages/babel-plugin-transform-svg-component/src/types.ts, packages/babel-plugin-transform-svg-component/src/variables.ts, packages/cli/src/__snapshots__/index.test.ts.snap, packages/cli/src/index.test.ts, packages/cli/src/index.ts, packages/core/src/config.ts, packages/plugin-jsx/src/index.test.ts, packages/plugin-jsx/src/index.ts, tsconfig.json
It default to "classic", the old behaviour. But it can be "automatic" (the recommended) or "classic-preact".
=> feat: support jsxRuntime

__fixtures__/custom-index-template.js, packages/cli/src/__snapshots__/index.test.ts.snap, packages/cli/src/dirCommand.ts, packages/cli/src/fileCommand.ts, packages/cli/src/index.test.ts, packages/cli/src/index.ts
Also run Prettier on index.js file.
Closes #570
=> feat(cli): allow all CLI options in config

README.md
It looks like this was intended to be a link, but was missing the URL
N/A
=> docs(readme): Fixing CRA link

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.ts.snap, packages/babel-plugin-transform-svg-component/src/index.test.ts, packages/babel-plugin-transform-svg-component/src/types.ts, packages/babel-plugin-transform-svg-component/src/variables.ts
=> fix(template): make it possible to use type in template

package-lock.json, packages/babel-plugin-svg-em-dimensions/README.md, packages/babel-plugin-svg-em-dimensions/src/index.test.ts, packages/babel-plugin-svg-em-dimensions/src/index.ts, packages/babel-preset/src/index.test.ts, packages/babel-preset/src/index.ts, packages/cli/src/__snapshots__/index.test.ts.snap, packages/cli/src/index.test.ts, packages/cli/src/index.ts, packages/core/src/__snapshots__/transform.test.ts.snap, packages/core/src/config.ts, packages/core/src/transform.test.ts
BREAKING CHANGE: using --icon as latest arg now requires "--"
Fix #571
=> feat: allow to specify icon size

packages/hast-util-to-babel-ast/src/index.test.ts, packages/hast-util-to-babel-ast/src/stringToObjectStyle.ts
=> fix: support CSS variables

website/pages/docs/custom-templates.mdx
I tried using the example code [here](https://react-svgr.com/docs/custom-templates/) and noticed that the docs still refer to `tpl.ast` which no longer exists on the template context argument.
=> Small text fix in custom-templates.mdx

website/pages/docs/migrate.mdx
I think this meant to say that it is the "last" version to support CommonJS, not "latest"
=> Small text fix in migrate.mdx

website/pages/docs/webpack.mdx
The [doc page of webpack](https://react-svgr.com/docs/webpack/#use-svgr-and-asset-svg-in-the-same-project) has incorrect  resourceQuery comment in code section.
```js
module.exports = {
module: {
rules: [
{
type: 'asset',
resourceQuery: /url/, // *.svg?react
},
{
test: /\.svg$/i,
issuer: /\.[jt]sx?$/,
use: ['@svgr/webpack'],
},
],
},
}
```
```js
import svg from './assets/file.svg?url'
import Svg from './assets/file.svg'
const App = () => {
return (
<div>
<Svg width="200" height="200" viewBox="0 0 3500 3500" />
</div>
)
}
```
Changed it from `// *.svg?react` to  `// *.svg?url`
=> docs: correct the resourceQuery comment in code

packages/rollup/package.json, packages/rollup/src/index.ts
This PR fixes 1 bug and 1 warning:
1. Bug https://github.com/gregberge/svgr/issues/651 - missing dependency
2. Fix for the warnings that rollup shows in console:
It should not break any existing tests.
=> Fixes for rollup plugin

packages/webpack/README.md, website/pages/docs/configuration-files.mdx, website/pages/docs/options.mdx
I'm updating `@svgr/cli` in a component library repo (https://github.com/curology/radiance-ui/pull/1307) and noticed some stale documentation with either incorrect instructions or out-of-date links. 
SVGO v2 has deprecated `.yml` files in favor of `.js` files (https://github.com/svg/svgo/commit/b1dafc67805a5637c940379d7576ac201675a79a removed the `.svgo.yml` file that was linked to, https://github.com/svg/svgo/pull/1328 mentions that config file can only be `js` now, etc.), and while Github is pretty good at directing links pointing to `master` to `main`, since this repo now uses `main`, it *does not* do this for `.js` files converted to `.ts`, and so those links are broken.
This PR updates both issues to try and make the docs less broken + more helpful to users working with this library. …
=> [Documentation] Update SVGO Usage + Repo Links

packages/plugin-svgo/src/index.test.ts, packages/plugin-svgo/src/index.ts
`svg.optimize()` can in [some cases](https://github.com/svg/svgo/blob/700f2031699e35da29efc19da74b8765aea127e6/lib/svgo.js#L36) return error, when passed SVG is invalid. There are some cases also, for instance when removing some namespace attributes that the SVG is invalid as a cause of that. When this happens `data` returned from plugin-svgo will be undefined, [causing this](https://github.com/gregberge/svgr/blob/main/packages/core/src/transform.ts#L13) to be undefined in the following iteration of the loop. This again causes obscure errors in some cases when running the following plugins. 
This depends on fixing the types for svgo: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58031 
Note: Marked this as breaking-change as it explicitly throws an error. There are other ways to …
=> breaking-change(plugin-svgo): handle potential errors from optimize

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.ts.snap, packages/babel-plugin-transform-svg-component/src/index.test.ts, packages/babel-plugin-transform-svg-component/src/index.ts
Fixes #660.
Snapshot test is provided to make sure comments are preserved.
=> feat: support comments in templates

packages/cli/src/dirCommand.ts
Prettier now gives warning when not being able to infer correct parser for files. It can infer by checking filepath or when explicitly setting parser. See issue and comment: https://github.com/prettier/prettier/issues/4763#issuecomment-409662425
This causes outputs such as:
There are different ways to solve this:
1. Pass in filename and let parser be inferred in format.
2. Fetch inferred parser and pass in explicit parser to format.
In this PR I've chosen the latter option as it feels more explicit. In plugin-prettier it is [hardcoded to babel](https://github.com/gregberge/svgr/blob/main/packages/plugin-prettier/src/index.ts#L15) but as I see it that might not be correct here?
Tested by running and verifying that prettier deprecation warning is gone.
=> fix(cli): pass in parser to prettier format to avoid deprecation warning

website/pages/docs/options.mdx
=> docs: improve options docs

packages/cli/src/__snapshots__/index.test.ts.snap, packages/cli/src/dirCommand.ts, packages/cli/src/index.test.ts
=> fix: use .ts extension for generated index

packages/core/package.json
The `lib/index.d.ts` file is not included in the npm package dist, correct the `types` file path in the `package.json` , same as the `typings` field.
=> fix(core): types path in package.json

package-lock.json, packages/rollup/package.json, packages/rollup/src/index.ts
[`rollup-pluginutils`](https://www.npmjs.com/package/rollup-pluginutils) has been renamed to [`@rollup/pluginutils`](https://www.npmjs.com/package/@rollup/pluginutils)
Fixes #686
Same module, same function, same signature, just renamed.
Ran `npm test` and `npm run build`, both passed.
=> chore(deps): upgrade deprecated rollup-pluginutils

.gitignore, website/pages/docs/webpack.mdx
When trying to use webpack 5's `resourceQuery` as defined in the previous docs, I kept getting a base64 string of the compiled react component not the svg.
This ended up erroring out all usage of `import svg from 'my-svg.svg?url` since it wasn't actually a base64 of the xml svg. I updated the docs with the fix I used to only have the svgr loader called when the resourceQuery is not url.
Also updated the`.gitignore` to ignore MacOS specific files in the future.
The `examples/webpack` didn't use the `resourceQuery` option so the only edits were made to the documentation text. I ran the gatsby doc app locally to check that it works and reflected the change in the right spot and then linted/tested the entire repo.
=> Update webpack docs when using SVGR and asset SVG in the same project

CHANGELOG.md
As CHANGELOG.md does **not** contain all major releases and breaking changes (ie. it is missing 6.0.0), the text "All notable changes to this project will be documented in this file" has been causing confusion - it has been removed (as it is not accurate) and a warning has been added to check Github releases.
No functional code changes.
=> Add CHANGELOG.md warning for missing releases, link to Github page

website/src/components/playground/Playground.js
I added a copy button in the playground JSX section so that the generated output can be copied with the click of a button. Please note that the copy feedback is still shown once per session regardless of the copy method, i.e., it works with both the button and/or ```cmd+c```. The button text changes from ```Copy``` to ```Copied!``` for two seconds and resets back to ```Copy```.
Please advice if anything else is needed for this section.
=> feat: add a copy button in the playground jsx output header

packages/cli/src/dirCommand.ts
When I use `svgr -d` to convert directory and there is a broken SVG file, the command failed with output:
```
Error in parsing SVG: Unexpected close tag
Line: 0
Column: 1578
Char: >
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```
Can not know which file is wrong.
=> chore(cli): output file name when error happen to handling a file

package.json, packages/babel-plugin-svg-dynamic-title/README.md, packages/babel-plugin-svg-dynamic-title/src/index.test.ts, packages/babel-plugin-svg-dynamic-title/src/index.ts, packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.ts.snap, packages/babel-plugin-transform-svg-component/src/index.test.ts, packages/babel-plugin-transform-svg-component/src/types.ts, packages/babel-plugin-transform-svg-component/src/variables.ts, packages/babel-preset/src/index.test.ts, packages/babel-preset/src/index.ts, packages/cli/README.md, packages/cli/src/__snapshots__/index.test.ts.snap, packages/cli/src/index.test.ts, packages/cli/src/index.ts, packages/core/src/__snapshots__/config.test.ts.snap, packages/core/src/__snapshots__/transform.test.ts.snap, packages/core/src/config.ts, packages/core/src/transform.test.ts, packages/plugin-jsx/src/index.ts, website/pages/docs/options.mdx, website/src/components/playground/config/settings.js
Fixes #714 
- Updated README.md and src files in `babel-plugin-svg-dynamic-title` to add a descProp
- the plugin now takes in a `tag` option indicating the attribute/element to add to the svg ('title' for title, or 'desc' for desc)
- Updated `babel-plugin-transform-svg-component` to add additional desc and descId attributes to the svg if descProp is true
- Updated `babel-preset` to add the `aria-describedby` attribute
- Added descProp to various options, cli-config, etc.
- Updated documentation to include a Description section
Simply `npm run test`! Existing tests have been slightly modified. New tests have been added to test the new feature.
=> feat(descProp): add descProp option

packages/babel-plugin-add-jsx-attribute/package.json, packages/babel-plugin-remove-jsx-attribute/package.json, packages/babel-plugin-remove-jsx-empty-expression/package.json, packages/babel-plugin-replace-jsx-attribute-value/package.json, packages/babel-plugin-svg-dynamic-title/package.json, packages/babel-plugin-svg-em-dimensions/package.json, packages/babel-plugin-transform-react-native-svg/package.json, packages/babel-plugin-transform-svg-component/package.json, packages/babel-preset/package.json, packages/core/package.json, packages/hast-util-to-babel-ast/package.json, packages/plugin-jsx/package.json, packages/plugin-prettier/package.json, packages/plugin-svgo/package.json, packages/rollup/package.json, packages/webpack/package.json
=> fix(package.json): fix exports

packages/babel-plugin-add-jsx-attribute/package.json, packages/babel-plugin-remove-jsx-attribute/package.json, packages/babel-plugin-remove-jsx-empty-expression/package.json, packages/babel-plugin-replace-jsx-attribute-value/package.json, packages/babel-plugin-svg-dynamic-title/package.json, packages/babel-plugin-svg-em-dimensions/package.json, packages/babel-plugin-transform-react-native-svg/package.json, packages/babel-plugin-transform-svg-component/package.json, packages/babel-preset/package.json, packages/core/package.json, packages/hast-util-to-babel-ast/package.json, packages/plugin-jsx/package.json, packages/plugin-prettier/package.json, packages/plugin-svgo/package.json, packages/rollup/package.json, packages/webpack/package.json
The recent exports change broke ESM imports. Attempting to `import '@svgr/core'` results in
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /code/node_modules/@svgr/core/package.json imported from ...
```
According to https://nodejs.org/api/packages.html#conditional-exports, a `default` key should be used here instead of `require` since it will work for both CJS and ESM. I made this change locally and verified ESM imports worked again.
=> Fix exports

packages/core/src/state.test.ts, packages/core/src/state.ts
Currently source file names that have spaces in them are not converted to component names the same way as the file names, e.g. from `Arrow up.svg` the component name will be `SvgArrowup` and the file name will be `SvgArrowUp.tsx`.
The PR fixes this discrepancy by *not* removing spaces from the file names before converting them to PascalCase.
Added a test case.
=> Support spaces in source file names

website/pages/docs/ecosystem.mdx
Updated the Vite plugin recommendation as the project listed in the current docs has been deprecated, see here: https://github.com/lucsky/vite-plugin-svgr/issues/5
None. This is a simple documentation change.
=> docs: update vite plugin recommendation

packages/babel-preset/src/index.test.ts, packages/babel-preset/src/index.ts, packages/cli/src/__snapshots__/index.test.ts.snap, packages/cli/src/__snapshots__/util.test.ts.snap, packages/core/src/__snapshots__/transform.test.ts.snap, packages/plugin-jsx/src/index.test.ts, packages/rollup/src/__snapshots__/index.test.ts.snap, packages/webpack/src/__snapshots__/index.test.ts.snap
=> feat(babel-preset): add attribute role="img" to the svg element

package-lock.json, packages/core/package.json
Fixes #781.
The 6.3.0 -> 6.3.1 changes were caused by just doing `npm install`.
=> fix(deps): add babel-preset to core dependencies

package-lock.json, packages/core/package.json
Installing @svgr/core with Yarn Modern (Yarn 2+) gives the following warning:
```
➤ YN0002: │ @svgr/core@npm:6.4.0 doesn't provide @babel/core (p0b84c), requested by @svgr/babel-preset
```
Fixes #785.
`npm run test` and `npm run lint` still pass.
=> Fix Yarn peer dependency warning from @babel/core

packages/babel-preset/src/index.test.ts, packages/babel-preset/src/index.ts, packages/cli/src/__snapshots__/index.test.ts.snap, packages/cli/src/__snapshots__/util.test.ts.snap, packages/core/src/__snapshots__/transform.test.ts.snap, packages/plugin-jsx/src/index.test.ts, packages/rollup/src/__snapshots__/index.test.ts.snap, packages/webpack/src/__snapshots__/index.test.ts.snap, website/pages/docs/options.mdx
Fixes #788 
#737 #750 defaulted to adding `role="img"` and #787 added `accessibilityRole="image"` for react-native on SVG Nodes.
The way this was added made it a breaking change for current consumers of svgr > 6.3.
Instead recommend adding documentation to the `svgProps` option that can be passed into any SVGR configuration with  how to add these defaults and reverted those changes.
The reasoning behind that is most consumers most-likely already handle accessibility within their applications and SVGR can just provide some guidance instead.
`npm run dev` from the `/website` directory after `npm install`
http://localhost:8000/docs/options/#svg-props
=> docs(a11y): revert #750 and add accessibility documentation for `svgProps` override

website/pages/docs/remix.mdx
The doc [page of remix](https://react-svgr.com/docs/remix/#install) has incorrect package installation list.
=> docs: fix typo in remix docs

website/pages/docs/next.mdx
This change makes the Next configuration provided in the docs usable in Next 13.
The new installation instructions are for a more advanced configuration than originally appeared in these docs, but the original did not actually work in Next 13, and the workaround took nearly as much code, so I've stuck with the slightly longer config here.
The code example is running in my local installation.
=> Update next documentation

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.ts.snap, packages/babel-plugin-transform-svg-component/src/index.test.ts, packages/babel-plugin-transform-svg-component/src/types.ts, packages/babel-plugin-transform-svg-component/src/variables.ts, packages/core/src/config.ts, packages/plugin-jsx/src/index.ts, website/pages/docs/options.mdx
Right now I can't find a way to integrate svgr with my workflow (parcel2 building a hyperapp-based website), as there are a couple of missing things:
- no way to specify a custom JSX import config via a config file
- no way to use the custom JSX import config to specify that we want to use the default import
```
$ cat ~/Projects/KaraKara/browser2/package.json | jq .svgr
{
"jsxRuntimeImport": {
"source": "hyperapp-jsx-pragma",
"defaultSpecifier": "h"
},
"icon": true,
"replace-attr-values": "#4d4d4d=currentColor"
}
$ npx svgr ~/Projects/KaraKara/browser2/src/static/favicon.svg | head -n 5
import h from "hyperapp-jsx-pragma";
const SvgFavicon = (props) => (
...
```
=> Allow hyperapp compatibility via config file

website/src/components/playground/config/settings.js
fix #817
Trim key and value when parse string setting to object
Tested locally, The SVG Props setting works fine even when a  new line occurs:
=> docs: trim key and value when parse string setting to object

website/src/components/playground/config/settings.js
fix #847 
I'm sorry, this [PR ](https://github.com/gregberge/svgr/pull/843)crashed the website playground.
```
const parseObject = (value) =>
value.split(',').reduce((obj, assignment) => {
const [left, right] = assignment.split('=')
return {
...obj,
[left.trim()]: right.trim(),
}
}, {})
```
`right` in the above function may be `undefined`, so `parseObject` will throw an error.
> Curious why the error is not visible in the console
The playground works even if  `REPLACE  ATTRIBUTES VALUE ` or  `SVG PROPS` are not set:
=> fix: parseObject error causes website broken

api/package-lock.json
Upgrade svgr deps to latest v7 in api.
Currently `descProp` in playground not take effect at all, it seems to be because the svgr dependency in the api is locked to 6.0.0:
Just delete the `svgr/api/package-lock.json` then re-run `npm install` to re-generate the new lockfile, then test it via postman as follows:
You can see that descProp is now in effect.
=> chore(api): upgrade deps to latest v7

__fixtures__/custom-index-template.js, packages/cli/src/dirCommand.ts, website/pages/docs/cli.mdx, website/pages/docs/custom-templates.mdx
index-template now receives an array of objects containing both the created component path (`path`) and the original svg path (`originalPath`).
It is a response to issue #858.
As before-mentioned, it responds to issue #858, that is, allow index templates to know the original file handled's path.
You can use this template. It should create an index.js file containing an object `map` containing the mapping between the original svg file name and the react component.
```js
const path = require('path');
function defaultIndexTemplate(filePaths) {
const entries = filePaths.map(({path: filePath, originalPath}) => {
const originalFileName = path.basename(
originalPath,
path.extname(originalPath),
);
const basename = path.basename(filePath, path.extname(filePath));
const exportName = …
```
=> feature: 858 Index template improvements

packages/babel-plugin-transform-svg-component/src/__snapshots__/index.test.ts.snap, packages/babel-plugin-transform-svg-component/src/variables.ts, packages/cli/src/__snapshots__/index.test.ts.snap
This PR changes `SVGProp` from value import to type import when the `--typescript` flag is supplied.
Here's an example of the change:
The change is quite straightforward. It adds a `importKind` parameter to the `getOrCreateImport` method so that both when importing the react and react-native versions of `SVGProps`, we can create the `ImportDeclaration` node with the right `importKind` parameter.
This addresses the warning for `verbatimModuleSyntax` [flag](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#verbatimmodulesyntax) in Typescript 5.0, seen below[they shipped the --verbatimModuleSyntax flag]
Note: this PR is branched off f20a753 because the build was failing in the newer commits.
This PR addresses #842 
I ran the jest tests and inspected the generated output to …
=> Change `SVGProps` from import to import type

packages/babel-plugin-transform-react-native-svg/src/index.ts
This PR resolved #891 
When updating the imports of react-native-svg there is no check on the importKind. This would cause a wrong update import and a crash in the cli. This bug occurs when combining expandProp, native and typescript in the config.
```js
import * as React from "react";
import Svg, { Path } from "react-native-svg";
//     ^^^   ^^^^^
import type { SvgProps, Svg, Path } from "react-native-svg";
//                      ^^^^^^^^^
```
```js
import * as React from "react";
import Svg, { Path } from "react-native-svg";
import type { SvgProps } from "react-native-svg";
```
Run the cli with expandProp, native and typescript in the config. It used to crash and complain about duplicate imports.
Thanks to @atomicpages for their investigative work, it helped me track the bug.
=> fix: :bug: fixed duplicate react-native-svg duplicate import

__fixtures__/withSvgoConfig/svgo.config.cjs, packages/cli/src/__snapshots__/index.test.ts.snap, packages/cli/src/index.test.ts, packages/cli/src/index.ts, packages/plugin-svgo/src/config.ts, website/pages/docs/configuration-files.mdx
In our vite project, since it is `"type": "module"` (ESM), the cli wouldn't accept svgo config files as a regular `.js` file that wasn't esm. This PR enables the cli to use `.cjs`.
Addresses 
- I ran the modified code in our vite environment and it accepted `svgo.config.cjs`
- I've added a test.
- I wasn't able to add error checking for ESM detection as I think jest is doing some funny things there?
Thank you for the wonderful library and let me know if I can do anything else to this PR 🎉
=> add support for svgo.config.cjs files in esm environments

packages/core/package.json, pnpm-lock.yaml
Upgrade to cosmiconfig 8.3.6, which fixes an unhandled exception when traversing parent directories looking for directories named `.config`. If a parent directory contained a file named `.config`, before this fix, generated React apps would fail to start. I documented this bug in https://github.com/facebook/create-react-app/issues/13355#issuecomment-1705159226 but I believe the issue originates from within this library.
I followed the steps documented in CONTRIBUTING.md.
=> chore: upgrade cosmiconfig

packages/babel-plugin-transform-react-native-svg/src/index.test.ts, packages/babel-plugin-transform-react-native-svg/src/index.ts
I was trying to use the babel-plugin-transform-react-native-svg separately in babel without svgr and hit an issue where it wouldn't update the import declaration.
I managed to pin it down to the new check added in #894. As per [the babel spec](https://github.com/babel/babel/blob/main/packages/babel-parser/ast/spec.md#importdeclaration) for imports, `importKind` will be `null | 'type' | 'typeof' | 'value'`. When using babel to parse an existing import, its being parsed as `'value'`...
I think its `null` when working with svgr because [when we add the import declaration to the AST](https://github.com/gregberge/svgr/blob/main/packages/babel-plugin-transform-svg-component/src/variables.ts#L133-L135), we don't specify the import kind parameter when calling `getOrCreateImport`.
Add a new test …
=> Fix check for type imports in transform-react-native-svg

website/pages/docs/next.mdx
=> Website, next.js instructions

website/pages/docs/next.mdx
Add instructions to next.js docs page to clarify how to add TypeScript support, e.g. for vscode autocomplete.
N/A, just docs
=> docs: update nextjs docs for TypeScript support instructions

website/src/components/playground/Playground.js
While using the website, I noticed that when you click the "Follow me on Twitter" button, it takes you to a random account with 22 followers instead of @gregberge_, the creator of this repo's twitter account as shown on his website, also linked in this repo.
The change is very small and uses only existing code, only swapping the handle in the link for the correct one. I tested it by copying the link and putting it into my browser to confirm it is correct
=> correct twitter handle link

website/pages/docs/options.mdx
The `ignoreExisting` and `indexTemplate` are not available anymore in the core API starting from v5 (but yet available when using the cli), this pull request reflects that change in the documentation.
=> docs: update docs about missing api options
