gregberge/svgr

README.md

Fix Webpack instructions in readme

---

.eslintignore
package.json
src/__snapshots__/index.test.js.snap
src/configToOptions.js
src/h2x/removeStyle.js
src/index.js
src/index.test.js
webpack.js

fix(jsx): remove style tag

---

README.md
src/__snapshots__/index.test.js.snap
src/cli/__snapshots__/index.test.js.snap
src/cli/index.js
src/cli/index.test.js
src/configToOptions.js

Add viewBox option that defaults to `true`

---

README.md
src/cli/dirCommand.js
src/cli/dirCommand.test.js
src/cli/index.js
src/configToOptions.js

Add custom file extension option

---

.babelrc
src/cli/__snapshots__/index.test.js.snap
src/cli/index.js
src/cli/index.test.js

fix: fix tabWidth option

---

README.md

docs(readme): document issuer

---

src/__snapshots__/index.test.js.snap
src/index.js
src/index.test.js

fix: handle filename with numbers

---

src/cli/__snapshots__/index.test.js.snap
src/configToOptions.js

Relative to https://github.com/zabute/gatsby-plugin-svgr/issues/8\#issuecomment-375467614

fix: fix width / height override

---

README.md

docs(readme): fix usage

---

README.md
src/__snapshots__/index.test.js.snap
src/cli/__snapshots__/index.test.js.snap
src/cli/index.js
src/cli/index.test.js
src/configToOptions.js
src/h2x/__snapshots__/titleProp.test.js.snap
src/h2x/titleProp.js
src/h2x/titleProp.test.js
src/index.test.js
src/transforms/wrapIntoComponent.js

feat(titleProp): add titleProp option

---

README.md
package-lock.json
package.json
rollup.js
src/__snapshots__/rollup.test.js.snap
src/rollup.js
src/rollup.test.js
src/transforms/wrapIntoComponent.js
yarn.lock

feat(rollup): add rollup plugin

---

packages/core/package.json
yarn.lock

Closes #126
Thanks @wtgtybhertgegh

chore(deps): remove unused deps

---

packages/webpack/src/index.js

Use proper source when using another loader before svgr/webpack

fix(webpack): Fix webpack loader when another loader used before

---

package.json
packages/cli/src/__snapshots__/index.test.js.snap
packages/core/package.json
packages/core/src/__snapshots__/convert.test.js.snap
packages/core/src/convert.test.js
packages/core/src/h2x/titleProp.js
packages/rollup/package.json
yarn.lock

fix: style & custom SVG properties

---

package.json
packages/cli/package.json
packages/rollup/package.json
packages/webpack/package.json
yarn.lock

chore: upgrade deps

---

website/package.json
website/server/index.js
website/yarn.lock

docs(website): enable cors on API

---

packages/rollup/src/index.js
packages/webpack/src/index.js

fix(webpack): use static babel config

---

package.json
packages/babel-plugin-transform-svg-component/src/index.test.js
packages/cli/package.json
packages/hast-util-to-babel-ast/package.json
packages/plugin-jsx/package.json
packages/rollup/package.json
packages/webpack/package.json
yarn.lock

Upgrade deps & add test

---

website/src/pages/docs/configuration-files.mdx
website/src/pages/docs/options.mdx

fixed supported

---

website/src/pages/docs/options.mdx

A couple of teeny tiny typos I found while browsing the docs
Just docs update

Small typos in options.mdx

---

now.json

chore(now): add public: true

---

netlify.toml
website/_redirects
website/gatsby-config.js
website/package.json
website/src/components/playground/CodeFund.js
website/src/components/playground/Playground.js
website/src/pages/404.mdx
website/src/pages/index.mdx
website/yarn.lock

docs: upgrade website

---

README.md

Include the contributing guidelines section.
N/A

[Docs]: add contributing guidelines section

---

README.md
website/src/pages/docs/jest.mdx

Updated Readme file and added usage guide to document how to use with Jest.
This fixes issue #278

Documented how to use with Jest

---

website/src/pages/docs/ecosystem.mdx

Providing an alternative to CRA that also supports server side rendering out-of-the-box
Irrelevant as only a website's mdx has changed

Add "React SSR Setup" to SVGR Inside section

---

packages/cli/README.md
packages/cli/src/index.js
website/src/pages/docs/options.mdx

My co-workers and I were working through a v4 to v5 regression in our application and noticed that there were multiple sources of truth for the docs, so it took us a little while to get on the same page with one another since we were looking at different pages 🙂 
This PR updates the following places to include all up-to-date features:
1. The CLI options 
1. The CLI Github README
1. The CLI options docs page on the website (very small fix)
No issues with `yarn run dev` arose, no lint issues from `yarn lint`, and no test issues with `yarn test`.

[Docs] Update CLI options + small website fix

---

package.json
packages/cli/package.json
packages/cli/src/__snapshots__/index.test.js.snap
packages/cli/src/index.test.js
packages/parcel-plugin-svgr/package.json
packages/parcel-plugin-svgr/src/__snapshots__/index.test.js.snap
packages/plugin-prettier/package.json
packages/rollup/package.json
packages/rollup/src/__snapshots__/index.test.js.snap
packages/webpack/package.json
packages/webpack/src/__snapshots__/index.test.js.snap
yarn.lock

chore: upgrade dependencies

---

website/src/components/playground/config/settings.js

doc(website): add new typescript option

---

packages/cli/src/dirCommand.js

fix(cli): fix index generation

---

packages/plugin-svgo/src/index.js

#412 add any SVGO config format support but missing .svgorc.js

feat(svgo): add .svgorc.js config file support

---

packages/plugin-prettier/package.json
packages/plugin-prettier/src/index.js
packages/plugin-svgo/package.json
packages/plugin-svgo/src/config.js
yarn.lock

Deepmerge has no dependencies and the package is smaller.
https://packagephobia.com/result?p=deepmerge
https://packagephobia.com/result?p=merge-deep
Check with existing tests

Replace merge-deep with smaller deepmerge

---

website/src/pages/docs/jest.mdx

fix: typo in jest docs

---

website/src/pages/docs/options.mdx

Added docs for `--filename-case` option introduced in https://github.com/gregberge/svgr/pull/136.

Add docs for --filename-case option

---

website/src/pages/index.js

I have replaced the word `Performances` with `Performance`. It's possibly a typo.
None/Not needed

Fixed a possible typo in the landing page

---

website/src/pages/docs/options.mdx

Documentation of the "Runtime config" options was wrong (copied from "Config file"?).
Not required

Fix documentation of "Runtime config"

---

website/README.md

Fix broken gatsbyjs.org link at website MD
Click on the link

Fix broken gatsbyjs.org link at website MD

---

website/pages/docs/rollup.mdx

docs(rollup): change url plugin

---

packages/hast-util-to-babel-ast/src/mappings.ts

feat: support mask-type property

---

api/api/svgr.js
website/pages/docs/options.mdx

- docs: document JSX runtime
- chore: fix playground

various fixes

---

package-lock.json
packages/webpack/package.json

perf: remove useless loader-utils package

---

examples/mocha-esm/__mocks__/svg.js
examples/mocha-esm/example.js
examples/mocha-esm/example.test.js
examples/mocha-esm/mock-loader.js
examples/mocha-esm/package.json
package-lock.json
website/pages/docs/jest.mdx
website/pages/docs/mocha.mdx

docs: configure mocha with SVGR

---

website/pages/docs/what-is-svgr.mdx

Fixes a small typo I saw.
❌ threw = throwing a ball
✅ through = continuing towards something

Fixes misspelling in docs

---

website/gatsby-config.js

docs: fix edit in GitHub links

---

packages/rollup/README.md

This simply fixes the link to the rollup plugin's source file in its readme

Fix link in rollup plugin readme

---

website/pages/docs/getting-started.mdx

Grammar fixes

---

website/pages/docs/migrate.mdx

docs(website): Correct <Get Ready For ESM> article link

---

packages/babel-preset/src/index.test.ts
packages/babel-preset/src/index.ts

fix: fix duplicate plugin/preset detected error

---

packages/babel-preset/src/index.test.ts
packages/babel-preset/src/index.ts
website/package-lock.json

Fixes 'role' attribute introduced in #750 for react-native
Upon generation for `native`, instead of web specific `role="img"` attribute, there should be the react-native equivalent `accessibilityRole="image"`.

feat(babel-preset): fix 'role' attribute on svg element for react native

---

website/pages/docs/getting-started.mdx
website/pages/docs/remix.mdx

I was working on a [Remix](https://remix.run/) project and wanted to automatize SVG transformation in the app in development time but didn't find any guide for that in the documentation but I found [this answer](https://stackoverflow.com/a/72275844/14751864) on StackOverflow so I added that to the docs website for future users.
Run:
```
npm i
npm run build
npm run test
```

docs: document remix configuration

---

website/pages/docs/options.mdx

fix tables in options.mdx

---

website/src/components/playground/config/settings.js

Add `dimensions`, `exportType`, `namedExport`, `jsxRuntime` settings in playground:

chore(website): add dimensions, exportType, namedExport and jsxRuntime settings in playground

---

packages/core/src/config.ts

Fix custom config via rc file

---

CHANGELOG.md

Add breaking change for webpack version to v6. closes #665

---

website/pages/docs/next.mdx

This part is missing for nextjs setup to work.

docs: nextjs setup

---

LICENSE

Revert "Update LICENSE, fix copyright license year"

---

website/pages/docs/options.mdx

in fact, the `@svgr/cli` can accept indexTemplate option, but marked as `not available` on docs

[docs] update index-template API Override docs
